version: '3.8'

services:
  localai:
    image: localai/localai:latest
    container_name: localai-server
    ports:
      - "${LOCALAI_PORT}:8080"
    environment:
      - DEBUG=true
      - MODELS_PATH=/models/mistral
    volumes:
      - ./models:/models
    command: ["/usr/bin/local-ai", "--config-file", "/models/mistral/config.yaml"]
    restart: unless-stopped
volumes:
  localai_models:
    driver: local
